---
title: "test"
author: "Marium Tapal"
date: "3/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 6)
```

```{r}
library(leaflet)
library(readxl)
library(janitor)
library(tidyverse)
library(readtext)
library(reactable)

data <- read_xlsx("data.xlsx", skip = 1) %>% clean_names()
map <- read_csv("mapDataFR.txt")
vaccines_am <- read_xlsx("covid19report.xlsx", sheet = "Age - municipality", skip = 1)
vaccines_rem <- read_xlsx("covid19report.xlsx", sheet = "Race and ethnicity - muni.", skip = 1)
```


```{r}
vaccines_am2 <- vaccines_am %>%
  filter(`Age Group` != "Total") %>%
  filter(`Fully vaccinated individuals` != "*" | `Proportion of town fully vaccinated individuals` != "*") %>%
  filter(County != "Unspecified") %>%
  mutate(
    `Fully vaccinated individuals` = as.numeric(`Fully vaccinated individuals`),
    `Proportion of town fully vaccinated individuals` = as.numeric(`Proportion of town fully vaccinated individuals`)
  ) %>%
  select(c(County, Town, `Age Group`, Population, `Fully vaccinated individuals`, `Proportion of town fully vaccinated individuals`))
vaccines_am2$Population <- round(vaccines_am2$Population, 0)
vaccines_am2$`Proportion of town fully vaccinated individuals` <- round(vaccines_am2$`Proportion of town fully vaccinated individuals`, 3)
vaccines_am2 <- vaccines_am2[, c(2, 1, 3, 4, 5, 6)]
reactable(vaccines_am2, searchable = TRUE, filterable = TRUE, theme = reactableTheme(
  borderColor = "#dfe2e5",
  stripedColor = "#f6f8fa",
  highlightColor = "#f0f5f9",
  cellPadding = "8px 12px",
  style = list(fontFamily = "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif"),
  searchInputStyle = list(width = "100%")
))
```


```{r}
# leaflet map
map %>%
  leaflet() %>%
  addTiles() %>%
  addTiles(group = "Open Street Maps") %>%
  addCircleMarkers(
    data = map, radius = 5,
    color = "purple",
    popup = map$name
  ) %>%
  setView(lng = -71.47275, lat = 42.24943, zoom = 7)
```
